### PR TITLE
Perf improvements

### PR DESCRIPTION
**Pull request by divdavem**
Hi @piuccio!

I hope you are fine!

As I am working on adding code coverage to aria-templates, I am opening this PR to improve node-coverage. It basically improves performance so that our [aria-templates](https://github.com/ariatemplates/ariatemplates) build can complete with code coverage enabled in less than 30 min instead of more than an hour (at which time travis-ci stops the build). Cf the report [here](https://codecov.io/gh/divdavem/ariatemplates/branch/coverage)!

It would be good if you could have a look at this PR, integrate it, and release a new major version (it is not completely backward-compatible).
If you do not have time for this project anymore (which I understand, of course!), please tell me (we could then do differently, probably publishing it to npm under a different name).

The main change in this PR is to clearly separate two kinds of data:
- "staticInfo": data about the instrumented file itself (list of statement ids, condition ids, function ids, highlighted code)
- "run": info about the code that was actually run. This includes the counters for each statement, condition or function that were actually executed at least once.

There is normally no need to include the "staticInfo" part in the instrumented files and have that info be sent to the browser and back to the server.
It is only needed on the server, along with the "run" part to compute and display coverage results on the server.

This commit makes it possible to create a JSON file containing the static part which will allow not to store it in instrumented files themselves, thus reducing the size of instrumented files and improving performance when calling submit.

This commit also removes the stack of all function calls that is built when function coverage is enabled, as it is usually very big, takes a lot of time to be sent to the server, and is not very useful. Instead, there is now a counter for each function in the same way as it is done for statement coverage.

Thank you!

### CODE REVIEW

**Comment by piuccio** [comment]
Hi David

I didn't know you guys were still using this project for code coverage. Is it in any way better that alternatives like istanbul?

Anyway, I don't have time or interest to maintain the project, I'll make you a contributor. If you send me your npm handle I'll give you publish access.

As for the function stack calls, it was an experiment to see if it could help debugging weird race conditions, but I agree that on any reasonably size app it's huge and almost impossible to understand.

Thanks for the PR

**Comment by divdavem** [comment]
Thank you @piuccio for your answer.

It is true that there are other alternatives, but as node-coverage is already integrated inside attester, it was simpler to just do those changes in order to improve performance and add coverage to Aria Templates and to other projects which are already using attester, rather than integrating a very different solution.

Thank you for giving us publish access on npm. We would probably push using the [ariatemplates](https://www.npmjs.com/~ariatemplates) account.

**Comment by piuccio** [comment]
you should have access now, have fun

**Comment by divdavem** [comment]
@piuccio Thank you!

**Pull request merged**
